### ISSUE TITLE
Not solved

### ISSUE THREAD

**Issue by ashkanjalaliQ** [a-maliarov/amazon-captcha-solver#1]
I constantly receive the message "not solved". What should I do?

My Code:
```
from amazoncaptcha import AmazonCaptcha

captcha = AmazonCaptcha('Captcha.jpg')
solution = captcha.solve()

print(solution)
```
Output:
`>>> Not solved`

**Comment by a-maliarov** [comment]
Hi, your code sample implies that you are downloading a captcha image, and then passing it to the function.

Please, provide the code, where you download the image, so I can try to replicate the problem.

**Comment by a-maliarov** [comment]
Please, reopen the issue in the "Constantly Not Solved" issue template and provide all the information.
